name: "WCW/nWo Thunder (main executable)"
sha1: 8c0058f2dec7b329494e234bda813dff60510c57
options:
  basename: slus_007.79
  target_path: disc/SLUS_007.79
  elf_path: build/slus_007.79.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  asm_path: asm/slus_007.79
  src_path: src/slus_007.79
  build_path: build
  # create_asm_dependencies: True

  ld_script_path: linker/slus_007.79.ld
  ld_dependencies: True

  find_file_boundaries: False
  gp_value: 0x8007B5AC

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - config/symbol_addrs.slus_007.79.txt
  reloc_addrs_path:
    - config/reloc_addrs.slus_007.79.txt

  undefined_funcs_auto_path: linker/undefined_funcs_auto.slus_007.79.txt
  undefined_syms_auto_path: linker/undefined_syms_auto.slus_007.79.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    # bss_size: Please fill out this value when you figure out the bss size
    subsegments:
      - [0x800, rodata, 800]
      - [0x10760, asm, main]
      - [0x10C64, asm, 10C64]
      - [0x11B10, c, cache_file_pos]
      - [0x11B60, asm, 11B60]
      - [0x14C1C, asm, decode_data]
      - [0x14CB0, asm, 14CB0]
      - [0x14CC4, c, movie]
      - [0x156C8, asm, 156C8]
      - [0x3A3F4, data, 3A3F4] # estimated
  - [0x5C000]
