name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Download ROM
        run: aws s3 cp s3://${{ secrets.S3_BUCKET }}/thunder/SLUS_007.79 SLUS_007.79

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --quiet install bchunk binutils-mips-linux-gnu build-essential cpp-mips-linux-gnu gcc-mips-linux-gnu git python3

      - name: Install Python packages
        run: python3 -m pip install -r requirements.txt

      - name: Make
        env:
          COMPARE: 0
        run: |
          make setup
          make

      - name: Echo generated executable checksum
        run: echo sha256sum ./build/THUNDER.EXE
